inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/*.gemspec'
    - '**/Gemfile'
    - '**/Rakefile'

Style/AsciiComments:
  Exclude:
    - 'lib/raheui/io.rb'
    - 'lib/raheui/code.rb'
    - 'spec/raheui/code_spec.rb'
