language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
  - jruby-9.0.0.0.pre1
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-9.0.0.0.pre1
    - rvm: jruby-head
    - rvm: rbx-2
before_install:
  - gem update --system
