language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - rbx-2
matrix:
  include:
    - rvm: jruby-19mode
      env: JRUBY_OPTS="-Xcli.debug=true --debug"
    - rvm: jruby-9.0.0.0
      env: JRUBY_OPTS="-Xcli.debug=true --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="-Xcli.debug=true --debug"
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-9.0.0.0
    - rvm: jruby-head
    - rvm: rbx-2
before_install:
  - gem update --system
